### PR TITLE
Tweak violation message in `prefer-message-ids` rule

### LINKED ISSUE #354: Error: Use `messageId` instead of `message` is incorrect for field `desc`
This error will show if the suggestion has `desc` instead of `messageId`

The error message is misleading

I am willing to submit a PR

### PR DESCRIPTION
**Pull request by nopeless**
Fixes #354

### CODE REVIEW

**Comment by nopeless** [comment]
@bmish

File: lib/rules/prefer-message-ids.js [hunk 1]
```diff
@@ -23,7 +23,10 @@ module.exports = {
     messages: {
       messagesMissing:
         '`meta.messages` must contain at least one violation message.',
-      foundMessage: 'Use `messageId` instead of `message`.',
+      // Currently the codebase does not distinguish between `message` and `desc`.
+      // `utils.collectReportViolationAndSuggestionData` returns `message` for both.
+      foundMessage:
+        'Use `messageId` instead of `message` (for reports) or `desc` (for suggestions).',
```
Comment (bmish) [inline lib/rules/prefer-message-ids.js:29]:
```suggestion
        'Use `messageId` instead of `message` (for violations) or `desc` (for suggestions).',
```

File: lib/rules/prefer-message-ids.js [hunk 2]
```diff
@@ -23,7 +23,10 @@ module.exports = {
     messages: {
       messagesMissing:
         '`meta.messages` must contain at least one violation message.',
-      foundMessage: 'Use `messageId` instead of `message`.',
+      // Currently the codebase does not distinguish between `message` and `desc`.
+      // `utils.collectReportViolationAndSuggestionData` returns `message` for both.
```
Comment (bmish) [inline lib/rules/prefer-message-ids.js:27]:
```suggestion
```

I think we can omit this comment. It's helpful context for the PR description but we probably don't need a comment for it.

**Review by bmish — COMMENTED** [review]
Please include `Fixes #354` (without backticks) in the PR description to link the PR and issue.

**Comment by nopeless** [comment]
rebased, commmit history clean @bmish

**Review by bmish — APPROVED** [review]
Thanks!
